### ISSUE TITLE
packageDaffodilBin needs warning if ignored because packageDaffodilBinInfos is not defined

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-sbt#56]
My build.sbt:
```
name := "dfdl-mySchema"

organization := "com.owlcyberdefense"

version := "1.0.0-SNAPSHOT"

// for details about DaffodilPlugin settings, see https://github.com/apache/daffodil-sbt
enablePlugins(DaffodilPlugin)

daffodilFlatLayout := true

daffodilVersion := daffodilPackageBinVersions.value.head

daffodilPackageBinVersions := Seq("3.5.0", "3.8.0", "3.7.0")

```
When I issue `sbt clean test packageDaffodilBin` test runs, but nothing is created in target directory.

**Comment by stevedlawrence** [comment]
You need to tell the plugin what schema to compile using `daffodilPackageBinInfos`.

Also, if your tdml tests use the saved parser file you need to set `daffodilTdmlUsesPackageBin := true`.

Maybe we should output a warning if the `packageDaffodilBin` task is run but either `daffodilPackageBinVersions` or `daffodilPackageBinInfos` is empty? One or both of those being empty means `packageDaffodilBin` won't do anything.

**Comment by mbeckerle** [comment]
A warning that it is being ignored would be a good fix.  I'll change title of this issue.

**Comment by stevedlawrence** [comment]
I think the schema path might require a leading `/` since it's a resource path. Maybe we should also warn if it's that's missing?

**Comment by stevedlawrence** [comment]
As part of this, we should improve our warnings/errors related to daffodilPackageBin. We should error if a resource path does not start with a `/`. We should also improve our error related to "duplicate classifiers" to make it more human friendly. It's not clear what "duplicate classifiers" even means. We should make change this error message so it's more obvious what the problem is and how to fix it.

**Comment by stevedlawrence** [comment]
That's fair. I think we could make it so that if `root` is defined but `name` is `None` then we just default to using root as the name, maybe with QName prefixes stripped off or something. One downside is you couldn't specify a root without making the resulting name more verbose, but maybe that's not a big deal, since if you really wanted that you could just specify the root element first in the schema and you wouldn't have to provide a root parameter.
